# Generated by Django 5.0.7 on 2024-07-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(null=True, upload_to="movie_image_file_path"),
        ),
    ]
