# Generated by Django 5.0.7 on 2024-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_astronomyshow_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="astronomy_show",
            field=models.ManyToManyField(
                related_name="astronomy_shows", to="planetarium.showtheme"
            ),
        ),
    ]
