# Generated by Django 5.0.7 on 2024-08-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_astronomyshow_astronomy_show"),
    ]

    operations = [
        migrations.RenameField(
            model_name="astronomyshow",
            old_name="astronomy_show",
            new_name="themes",
        ),
    ]
