# Generated by Django 5.0.7 on 2024-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0004_rename_astronomy_show_astronomyshow_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="astronomyshow",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="astronomy_shows", to="planetarium.showtheme"
            ),
        ),
    ]
